version: "3.9"

services:

  # -------------------------------
  # NGINX service
  # -------------------------------
  nginx:
    image: nginx:1.26.3-alpine
    container_name: cansat-nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
    networks:
      - cansatnet

  # -------------------------------
  # Mariadb service
  # -------------------------------
  mariadb:
    image: mariadb:11.4.10-noble
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DBHaacht26
      MYSQL_DATABASE: cansatdb
      MYSQL_USER: cansatuser
      MYSQL_PASSWORD: SkyByte26
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cansatnet

  # -------------------------------
  # phpMyAdmin service
  # -------------------------------
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: cansatuser
      PMA_PASSWORD: SkyByte26
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - cansatnet    

  # -------------------------------
  # Mosquitto MQTT broker service
  # -------------------------------
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - cansatnet

  # -------------------------------
  # MQTT to WebSocket bridge service
  # -------------------------------
  mqtt_to_ws:
    build: ./csv2json
    container_name: mqtt_to_ws
    depends_on:
      - mosquitto
    ports:
      - "8765:8765"  
    networks:
      - cansatnet

  # -------------------------------
  # WebSocket client service
  # -------------------------------
  ws_client:
    build: ./ws_client
    container_name: ws_client
    depends_on:
      - mqtt_to_ws
      - mariadb
    networks:
      - cansatnet

# -------------------------------
# Volumes and Networks
# -------------------------------
volumes:
  mariadb_data:

networks:
  cansatnet:
    driver: bridge